{% set name = "nvidia-ml-py" %}
{% set version = "12.550.52" %}
{% set sha256 = "dfedd714335c72e65a32c86e9f5db1cd49526d44d6d8c72809d996958f734c07" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
  run_constrained:
    # Packages that conflict with nvidia-ml-py
    # Both packages install pynvml.py
    - nvidia-ml ==9999999999
    - pynvml ==9999999999

test:
  imports:
    - pynvml
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.nvidia.com
  summary: Python Bindings for the NVIDIA Management Library
  license: BSD-3-Clause
  license_family: BSD
  license_file: README.txt
  dev_url: https://developer.nvidia.com/nvidia-management-library-nvml
  doc_url: https://docs.nvidia.com/deploy/nvml-api/index.html

extra:
  recipe-maintainers:
    - XuehaiPan
